### ISSUE TITLE
Ran an entire game on Saturday

### ISSUE THREAD

**Issue by fougerec** [jalensailin/mvrpg#21]
Had the opportunity to run an entire game on Saturday so here's some feedback from that.

- [x] The core system works well.  No glitches came up. The system for rerolling dice with Edge and keeping the best functioned as did automatically rerolling from trouble.
- [x] There's no way to add an Edge after a roll is made, most commonly with the Aid Teammate reaction, which means there's no way to reroll without doing it manually.  If this could be something that could be implemented that would be great.

Most of the rest are QOL things.

- [x] Detecting the appropriate defense so automating if it was a success or not.  Even a field where a DC could be inputted for a non-combat roll would be nice. (edit: see issue #25)
- [x] As mentioned - adjusting the condition markers from the generic/5e ones to Marvel specific ones. (edit: see issue #20)
- [x] A way to adjust damage for things like Sturdy or Uncanny to take into account DR. (edit: see issue #31)
- [x] An item type for "Weapons" (edit: see issue #2)

As is we ran for 3 hours without any issues that we wouldn't have had at the table.

**Comment by jalensailin** [comment]
This is very helpful information. Thank you!

**Comment by jalensailin** [comment]
> There's no way to add an Edge after a roll is made, most commonly with the Aid Teammate reaction, which means there's no way to reroll without doing it manually. If this could be something that could be implemented that would be great.

This should now be addressed in the latest update. Note: to download the latest update you may need to manually uninstall and reinstall via manifest link

**Comment by jalensailin** [comment]
I updated the original comment and turned the numbered list into checklist items so that we can keep track. I will check things off if (1) they have been addressed or (2) if there is a separate issue open for them

**Comment by jalensailin** [comment]
all bullet points now either have been addressed or have open issues. closing this one so we can track everything separately. thanks again!
